### ISSUE TITLE
Loading warnings

### ISSUE THREAD

**Issue by thecrypt0hunter** [RedstonePlatform/Redstone#19]
Networks/RedstoneNetworks.cs(1,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneNetworks.cs(2,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(1,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(69,13): warning SA1009: Closing parenthesis must not be preceded by a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(116,13): warning SA1009: Closing parenthesis must not be preceded by a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(151,114): warning SA1013: Closing brace must be preceded by a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(1,1): warning SA1652: Enable XML documentation output [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(35,66): warning SA1005: Single line comment must begin with a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(35,78): warning SA1028: Code must not contain trailing whitespace [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(141,41): warning SA1028: Code must not contain trailing whitespace [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneNetworks.cs(1,1): warning SA1652: Enable XML documentation output [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneNetworks.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(119,61): warning SA1116: The parameters must begin on the line after the declaration, whenever the parameter span across multiple lines [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(119,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(120,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(124,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(124,88): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(124,96): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(124,104): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(125,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(125,88): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(125,96): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(125,104): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(103,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(104,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(55,13): warning SA1111: Closing parenthesis must be on line of last parameter [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(101,13): warning SA1111: Closing parenthesis must be on line of last parameter [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(69,13): warning SA1111: Closing parenthesis must be on line of last parameter [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(116,13): warning SA1111: Closing parenthesis must be on line of last parameter [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(56,13): warning SA1009: Closing parenthesis must not be preceded by a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(104,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(105,80): warning SA1119: Statement must not use unnecessary parenthesis [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(102,13): warning SA1009: Closing parenthesis must not be preceded by a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(56,13): warning SA1111: Closing parenthesis must be on line of last parameter [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(102,13): warning SA1111: Closing parenthesis must be on line of last parameter [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(164,57): warning SA1118: The parameter spans multiple lines [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneMain.cs(168,20): warning SA1117: The parameters must all be placed on the same line or each parameter must be placed on its own line. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(1,1): warning SA1652: Enable XML documentation output [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneRegTest.cs(34,1): warning SA1028: Code must not contain trailing whitespace [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(55,13): warning SA1009: Closing parenthesis must not be preceded by a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(101,13): warning SA1009: Closing parenthesis must not be preceded by a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(1,1): warning SA1652: Enable XML documentation output [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(109,17): warning SA1005: Single line comment must begin with a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(110,17): warning SA1005: Single line comment must begin with a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(111,17): warning SA1005: Single line comment must begin with a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(116,17): warning SA1005: Single line comment must begin with a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Networks/RedstoneTest.cs(121,17): warning SA1005: Single line comment must begin with a space. [/home/thecryptohunter/projects/Redstone/src/Redstone/Core/Redstone.Core/Redstone.Core.csproj]
Program.cs(1,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(2,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(3,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(4,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(5,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(6,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(7,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(8,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(9,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(10,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(11,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(12,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(13,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(14,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(15,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(16,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(17,1): warning SA1200: Using directive must appear within a namespace declaration [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(37,1): warning SA1507: Code must not contain multiple blank lines in a row [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(1,1): warning SA1652: Enable XML documentation output [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Program.cs(53,21): warning SA1503: Braces must not be omitted [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Properties/AssemblyInfo.cs(1,1): warning SA1652: Enable XML documentation output [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]
Properties/AssemblyInfo.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/home/thecryptohunter/projects/Redstone/src/Redstone/Programs/Redstone.RedstoneFullNodeD/Redstone.RedstoneFullNodeD.csproj]

**Comment by dirty-harry** [comment]
These are all style cop warnings.  Happy to sort if you want me to.

"If you migrate a project to Visual Studio 2017, you might suddenly be faced with a large number of code analysis warnings. If you aren't ready to fix the warnings and want to become productive right away, you can baseline the analysis state of your project. From the Analyze menu, select Run Code Analysis and Suppress Active Issues."

**Comment by thecrypt0hunter** [comment]
Not an issue for compiled binary so closing
